M12_HW/Models/Product.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace M12_HW.Models
{
    public class Product
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string? Name { get; set; }

        [Required]
        [Precision(10, 2)]
        public decimal Price { get; set; }

        [Required]
        [StringLength(1024)]
        public string? Description { get; set; }

        [NotMapped]
        public IFormFile? ImageData { get; set; }
        public string? ImageType { get; set; }
        public byte[]? ImageFile { get; set; }

        public override string ToString() => $"Id: {Id}, Name: {Name}, Price: {Price}, Description: {Description}";
    }
}

M12_HW/Controllers/API/ProductController.cs
using M12_HW.Models;
using M12_HW.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace M12_HW.Controllers.API
{
    //http://localhost:5247/api/product
    [Route("api/[controller]")]
    [ApiController]
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    public class ProductController : Controller
    {
        private readonly IServiceProducts _serviceProducts;
        public ProductController(IServiceProducts serviceProducts)
        {
            _serviceProducts = serviceProducts;
        }
        [HttpGet]
        public async Task<IActionResult> GetJsonAsync()
        {
            var products = await _serviceProducts.ReadAsync();
            if(products != null)
            {
                return Ok(products);
            }
            else
            {
                return NotFound(new { status = "404" });
            }
        }
        //http://localhost:5247/api/product/4
        [HttpGet("{id}")]
        public async Task<IActionResult> GetProductById(int id)
        {
            var product = await _serviceProducts.GetByIdAsync(id);
            if(product != null)
            {
                return Ok(product);
            }
            return NotFound(new { status = "404" });
        }
        //Method: POST 
        //http://localhost:5247/api/product
        //Request:
        //Body
        //{
        //  Id: 0,
        //  Name: "A new Product",
        //  Price: 25,50,
        //  Description: "Some description"
        //}
        [HttpPost]
        public async Task<IActionResult> CreateProduct([FromBody] Product product)
        {
            if(product != null)
            {
                var result = await _serviceProducts.CreateAsync(product);
                return Ok(product);
            }
            return BadRequest(new { state = "Product is null ..." });
        }
        //Method: PUT 
        //http://localhost:5247/api/product/4
        //Request:
        //Body
        //{
        //  Id: 4,
        //  Name: "The product for update",
        //  Price: 25,50,
        //  Description: "Some description"
        //}
        [HttpPut("{id}")]
        public async Task<IActionResult> UpdateProduct(int id, [FromBody] Product product)
        {
            if (product != null)
            {
                var result = await _serviceProducts.UpdateAsync(id, product);
                return Ok(product);
            }
            return BadRequest(new { state = "Product is null ..." });
        }
        //Method: DELETE 
        //http://localhost:5247/api/product/4
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteProduct(int id)
        {
            var result = await _serviceProducts.DeleteAsync(id);
            if(result)
            {
                return Ok(new { status = "Ok!" });
            }
            return BadRequest(new { status = "Bad!" });
        }
    }
}

M12_HW/Controllers/CartController.cs
using M12_HW.Services;
using Microsoft.AspNetCore.Mvc;

namespace M12_HW.Controllers
{
    public class CartController : Controller
    {
        private readonly IServiceCart _cartService;

        public CartController(IServiceCart cartService)
        {
            _cartService = cartService;
        }

        public async Task<IActionResult> Index()
        {
            var cart = await _cartService.GetCartAsync();
            return View(cart);
        }

        [HttpPost]
        public async Task<IActionResult> Add(int productId)
        {
            await _cartService.AddToCartAsync(productId);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Remove(int id)
        {
            await _cartService.RemoveFromCartAsync(id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Clear()
        {
            await _cartService.ClearCartAsync();
            return RedirectToAction("Index");
        }
    }
}

M12_HW/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using M12_HW.Models;
using M12_HW.Services;
using System.Threading.Tasks;

namespace M12_HW.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceProducts _serviceProducts;
        public ProductController(IServiceProducts serviceProducts)
        {
            _serviceProducts = serviceProducts;
        }

        [HttpGet]
        public async Task<ViewResult> Index()
        {
            var products = await _serviceProducts.ReadAsync();
            return View(products);
        }
        [HttpGet] //https://localhost:port/product/create
        public ViewResult Create() => View();

        [Authorize(Roles = "admin,moderator,employee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Description,ImageData")] Product product)
        {
            if (ModelState.IsValid)
            {
                using (var ms = new MemoryStream())
                {
                    await product.ImageData.CopyToAsync(ms);
                    product.ImageFile = ms.ToArray();
                }
                product.ImageType = product.ImageData.ContentType;
                await _serviceProducts.CreateAsync(product);
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        [Authorize(Roles = "admin,moderator,employee")]
        [HttpGet]
        public async Task<ViewResult> Update(int id)
        {
            var product = await _serviceProducts.GetByIdAsync(id);
            return View(product);
        }

        [Authorize(Roles = "moderator,admin,employee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, [Bind("Id,Name,Price,Description,ImageData")] Product product)
        {
            Console.WriteLine(product);
            if (ModelState.IsValid)
            {
                using (var ms = new MemoryStream())
                {
                    await product.ImageData.CopyToAsync(ms);
                    product.ImageFile = ms.ToArray();
                }
                product.ImageType = product.ImageData.ContentType;

                await _serviceProducts.UpdateAsync(id, product);
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        [Authorize(Roles = "admin,moderator,employee")]
        [HttpGet]
        // GET: http://localhost:[port]/products/delete
        // Display the product delete confirmation form
        public async Task<ViewResult> Delete()
        {
            return View();
        }

        [Authorize(Roles = "admin,moderator,employee")]
        [HttpPost]
        // POST: http://localhost:[port]/products/delete/{id}
        // Handle product deletion
        public async Task<IActionResult> Delete(int id)
        {
            bool result = await _serviceProducts.DeleteAsync(id); // Delete the product asynchronously
            if(result)
            {
                return RedirectToAction(nameof(Index)); // Redirect to the product list
            }
            return NotFound();
        }
        // GET: http://localhost:[port]/products/details/{id}
        // Displays details of a single product by ID
        public async Task<ViewResult> Details(int id)
        {
            var product = await _serviceProducts.GetByIdAsync(id); // Retrieve product by ID asynchronously
            return View(product); // Return the product details to the view
        }
    }
}

M12_HW/Views/Product/Create.cshtml
@model M12_HW.Models.Product
@{
    Layout = "_Layout";
    ViewData["Title"] = "Create Product";
}
<h2>Create Product</h2>

<form enctype="multipart/form-data" asp-controller="Product" asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input name="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Price">Price</label>
        <input name="Price" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <textarea name="Description" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label asp-for="ImageData">Product photo:</label>
        <input type="file" name="ImageData" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

M12_HW/Views/Product/Delete.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Delete Product";
}

<form asp-controller="Product" asp-action="Delete" method="post">
    <div class="form-group">
        <label for="id">Id</label>
        <input for="id" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Delete</button>
</form>

M12_HW/Views/Product/Details.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Details Product";
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Description</th>
            <th scope="col">Image</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.Id</td>
            <td>@Model.Name</td>
            <td>@Model.Price</td>
            <td>@Model.Description</td>
            <td>
                @if (Model.ImageFile != null && Model.ImageType != null)
                {
                    var base64 = Convert.ToBase64String(Model.ImageFile);
                    var imgSrc = $"data:{Model.ImageType};base64,{base64}";
                    <img src="@imgSrc" width="200" height="100" />
                }
            </td>
        </tr>
    </tbody>
</table>

M12_HW/Views/Product/Index.cshtml
@model IEnumerable<M12_HW.Models.Product>
@{
    Layout = "_Layout";
    ViewData["Title"] = "Read Products";
}
<h2>Products</h2>
<p>
    @if (User.IsInRole("admin") || User.IsInRole("employee") || User.IsInRole("moderator"))
    {
        <a asp-controller="Product"
           asp-action="Create"
           class="btn btn-primary">Create</a>
    }

    <a asp-controller="Cart"
       asp-action="Index"
       class="btn btn-success">Go to Cart</a>

    <a asp-controller="Home"
       asp-action="Index"
       class="btn btn-success">Home page</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Description</th>
            <th scope="col">Image</th>
            <th scope="col">Tools</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model)
        {
            <tr>
                <td>@product.Id</td>
                <td>@product.Name</td>
                <td>@product.Price</td>
                <td>@product.Description</td>
                <td>
                    @if(product.ImageFile != null && product.ImageType != null)
                    {
                        var base64 = Convert.ToBase64String(product.ImageFile);
                        var imgSrc = $"data:{product.ImageType};base64,{base64}";
                        <img src="@imgSrc" width="200" height="100"/>
                    }
                </td>
                <td>
                    @if (User.IsInRole("admin") || User.IsInRole("employee") || User.IsInRole("moderator"))
                    {
                        <a href="@Url.Action("Update", new { id = product.Id })"
                           class="btn btn-warning">Update</a>
                        <a href="@Url.Action("Delete", new { id = product.Id })"
                           class="btn btn-danger">Delete</a>
                    }

                    <a href="@Url.Action("Details", new { id = product.Id })"
                       class="btn btn-info">Details</a>


                    <form asp-controller="Cart" asp-action="Add" method="post" style="display:inline">
                        <input type="hidden" name="productId" value="@product.Id" />
                        <button type="submit" class="btn btn-primary">Add to Cart</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

M12_HW/Views/Product/Update.cshtml
@model M12_HW.Models.Product
@{
    Layout = "_Layout";
    ViewData["Title"] = "Update Product";
}
<h2>Update Product</h2>

<form enctype="multipart/form-data" asp-controller="Product" asp-action="Update" method="post">
    <div class="form-group">
        <label asp-for="Id">Id</label>
        @if(Model != null)
        {
            <input name="Id" class="form-control" value="@Model.Id" />
        }
        else
        {
            <input name="Id" class="form-control" />
        }

    </div>
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input name="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Price">Price</label>
        <input name="Price" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <textarea name="Description" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label asp-for="ImageData">Product photo:</label>
        <input type="file" name="ImageData" class="form-control" />
    </div>
    <button type="submit" class="btn btn-success">Update</button>
</form>